t = 0:0.01:10; 
x = zeros(size(t)); 
x(t >= 1 & t <= 2) = 1; 
h = x;  
y = conv(x, h) * 0.01;  
ty = 0:0.01:20; 
figure; 
subplot(3,1,1); 
plot(t, x, 'LineWidth', 1.5); 
title('Input Signal x(t)'); 
grid on; 
subplot(3,1,2); 
plot(t, h, 'LineWidth', 1.5); 
ylabel('Amplitude'); 
grid on; 
subplot(3,1,3); 
plot(ty, y, 'LineWidth', 1.5); 
title('System Response y(t) = x(t)*h(t)'); 
xlim([0 10]); 
grid on; 
